# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df697ed7d5f46f3f5639fcd65047bd8fd70a38ffa41111ffda596738a684981c5a72a0dcb03506e2a37deaecf9fd3b05227bd2544fbc34bbf1db33a1314be89

test:
  secret_key_base: 4277e480c0df03e19800e4a9b6b8a7dcd0d91c6e5abd6f64d8a22dd4156c15716ae7b44af6149d85f8034fc7e363d4ab403dd8d92f46b0d12edde1e1fac11f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
